find_path(GLIB_INCLUDE_DIR NAMES glib.h PATH_SUFFIXES glib-2.0)
find_path(GLIB_CONFIG_INCLUDE_DIR NAMES glibconfig.h PATH_SUFFIXES lib/glib-2.0/include)

find_library(GLIB_LIBRARY NAMES glib-2.0)
find_library(GOBJECT_LIBRARY NAMES gobject-2.0)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GLib DEFAULT_MSG GLIB_LIBRARY GLIB_INCLUDE_DIR GOBJECT_LIBRARY GLIB_CONFIG_INCLUDE_DIR)

if(GLIB_FOUND AND GOBJECT_LIBRARY)
    set(GLIB_LIBRARIES ${GLIB_LIBRARY} ${GOBJECT_LIBRARY})
    set(GLIB_INCLUDE_DIRS ${GLIB_INCLUDE_DIR} ${GLIB_CONFIG_INCLUDE_DIR})
endif()

mark_as_advanced(GLIB_LIBRARY GLIB_INCLUDE_DIR GOBJECT_LIBRARY GLIB_CONFIG_INCLUDE_DIR)
